--- # Deployment Configuration
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-app
  namespace: dev # Updated namespace to dev
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: "doaahemaid01/my-app:1.0"

---

--- # Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: dev # Updated namespace to dev
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
